import smartpy as sp

# NOT_ADMIN = "NOT_ADMIN"
# NOT_ADMIN_OR_MANAGER = "NOT_ADMIN_OR_MANAGER"
# INVALID_SIGN = "INVALID_SIGN"
# INVALID_CALLBACK = "INVALID_CALLBACK"
# PAUSED = "PAUSED"
# INVALID_USER = "INVALID_USER"
# INVALID_PRICE = "INVALID_PRICE"